config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'home/about' => 'home#about', as: 'about'
  root "home#top"

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }
  resources :books, only: [:new, :create, :index, :show, :edit, :update] do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  get'/search' => 'search#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: {minimum: 2,maximum: 20}
  validates :introduction, length: {maximum: 50}
  validates :email, presence:true,length: {minimum: 3,maximum: 30}
  validates :postal_code, format: {with: /\A[0-9]{7}\z/}
  validates :address_city, presence: true,length: {minimum: 1,maximum: 30}
  validates :address_street, presence: true,length: {minimum: 1,maximum: 40}
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  before_validation :set_address
  include JpPrefecture
  jp_prefecture :prefecture_code
  def set_address
    self.address=prefecture_name+address_city+address_street
  end
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
  def self.search(method,word)
                if method == "forward_match"
                        @posts = User.where("name LIKE?","#{word}%")
                elsif method == "backward_match"
                        @posts = User.where("name LIKE?","%#{word}")
                elsif method == "perfect_match"
                        @posts = User.where(name: "#{word}")
                elsif method == "partial_match"
                        @posts = User.where("name LIKE?","%#{word}%")
                else
                        @posts = User.all
                end
    end

  #登録時にメールアドレスを不要とする
  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end
  def create
    super
    UserMailer.registration_confirmation(resource).deliver unless resource.invalid?
  end
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end
  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end
  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
  	  @user = User.find(params[:id])
  	  @books = Book.all
  end

  def index
  	  @users = User.page(params[:page]).reverse_order
  	  @books = Book.all
  end
  def edit
  	  @user = User.find(params[:id])
      unless @user.id == current_user.id
        redirect_to user_path(current_user)
      end
  end
  def update
  	  @user = User.find(params[:id])
      if @user.update(user_params)
      flash[:notice] = "ユーザー情報更新しました。"
      redirect_to user_path(@user.id)
      else
        render 'edit'
      end
  end

  def follows
      @user = User.find(params[:id])
      @users = @user.followings
  end

  def followers
      @user = User.find(params[:id])
      @users = @user.followers
  end


  private
  def user_params
      params.require(:user).permit(:name, :profile_image, :introduction, :postal_code, :prefecture_code, :address_city, :address_street, :latitude, :longitude, :address)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb

  <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: " ", fallback: "no_image.jpg" %> 
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>ユーザー名</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>自己紹介</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>フォロー</th>
        <th>
          <%= link_to follows_user_path(user) do %>
            <strong id="following" class="stat">
              <%= user.followings.count %>
            </strong>
          <% end %>
        </th>
      </tr>
      <tr>
        <th>フォロワー</th>
        <th>
          <%= link_to followers_user_path(user) do %>
            <strong id="followers" class="stat">
              <%= user.followers.count %>
            </strong>
          <% end %>
        </th>
      </tr>
    </tbody>
  </table>
  <div class="row">
  <% if user == current_user %>
  
    <%= link_to "", edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
  <% else %>
      <% if user.followed_by?(current_user) %>
                <center><p><%=link_to "フォロー中", user_relationships_path(user.id), method: :delete,class:"btn btn-primary btn-sm" %></p></center>
            <% else %>
                <center><p><%=link_to "フォロー　", user_relationships_path(user.id), method: :post,  class:"btn btn-success btn-sm"  %></p></center>
            <% end %>

  <% end %>
  </div>

app/views/users/edit.html.erb
<div class="body">
</div>
<div class="col-xs-3">
  <% if @user.errors.any? %>
    <ul>
        <%= @user.errors.count %><span>error</span>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
  <% end %>
  <h2>ユーザー情報</h2>
  <%= form_for(@user) do |f| %>
    <label for="user_name">ユーザー名</label>
    <%= f.text_field :name, autofocus: true, class:"form-control", placeholder:"名前"%>
    <label for="user_image">写真</label>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
    <label for="user_introduction">自己紹介</label>
    <%= f.text_field :introduction, autofocus: true, class:"form-control", id:"inputEmail", placeholder:""%>
    <div class="field">
      <%= f.label :郵便番号 %><br />
      <%= f.text_field :postal_code, autofocus: true,class:"form-control" %>
    </div>

    <div class="field">
      <%= f.label :都道府県 %><br />
      <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name %>
    </div>

     <div class="field">
      <%= f.label :市区町村 %><br />
      <%= f.text_field :address_city, autofocus: true,class:"form-control" %>
    </div>

      <div class="field">
      <%= f.label :番地_建物_部屋番号 %><br />
      <%= f.text_field :address_street, autofocus: true,class:"form-control" %>
    </div>
    <br>
    <%= f.submit "更新" %>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="body">
</div>
<h2>フォロワー</h2>
<% if @users.count > 0 %>
  <table class='table'>
  <thead>
    <tr>
      <th>写真</th>
      <th>名前</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image_id, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if user.followed_by?(current_user) %>
   	            <p><%=link_to "フォロー中", user_relationships_path(user.id), method: :delete,class:"btn btn-primary" %></p>
            <% else %>
                <p><%=link_to "フォロー　", user_relationships_path(user.id), method: :post, class:"btn btn-success"  %></p>
            <% end %>

          <% end %>
        </td>
        <td><%= link_to '詳細ページ', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/follows.html.erb
<div class="body">
</div>
<h2>フォロー</h2>
<% if @users.count > 0 %>
  <table class='table'>
  <thead>
    <tr>
      <th>写真</th>
      <th>名前</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image_id, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if user.followed_by?(current_user) %>
                <p><%=link_to "フォロー中", user_relationships_path(user.id), method: :delete,class:"btn btn-primary" %></p>
            <% else %>
                <p><%=link_to "フォロー　", user_relationships_path(user.id), method: :post, class:"btn btn-success"  %></p>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to '詳細ページ', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/index.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="container2">
        <%= form_tag(search_path , method: :get) do %>
            <%= text_field(@search_content, :search_word)%>
            <%= select(@search_content, :search_model, [["書籍", "book"],["ユーザー","user"]])%>
            <%= select(@search_content, :search_method, [["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]])%>
            <%= submit_tag "検索" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="col-xs-12">
  <h3>ユーザー一覧</h3>
  <table class="table">
    <thead>
      <tr>
        <th>写真</th>
        <th>名前</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 20, 20, format: 'jpeg', class: " ", fallback: "no-image-icon.jpg" ,size:'20x20' %></td> 
          <td><%= user.name %></td>
          <td>フォロー数:<%= link_to follows_user_path(user) do %>
            <strong id="following" class="stat">
              <%= user.followings.count %>
            </strong>
          <% end %>
          </td>
          <td>フォロワー数:<%= link_to followers_user_path(user) do %>
            <strong id="followers" class="stat">
              <%= user.followers.count %>
            </strong>
            <% end %>
          </td>
          <td>
            <% if current_user != user %>
              <% if user.followed_by?(current_user) %>
                <p><%=link_to "フォロー中", user_relationships_path(user.id), method: :delete,class:"btn btn-primary btn-sm" %></p>
            <% else %>
                <p><%=link_to "フォロー　", user_relationships_path(user.id), method: :post, class:"btn btn-success btn-sm"  %></p>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to "詳細ページ", user_path(user) %><td>
        </tr>
      <% end %>
      <%= paginate @users %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="body">
</div>
<% if flash[:notice] %>
  <div class="flash">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>
<div class="col-xs-3">
	<h3><%= @user.name %>さんのページ</h3>
	<%= render 'info', user: @user,now: ''%>
	<br>
	<% if @user.id == current_user.id %>
	<div class="container">
		<script type="text/javascript">
		  function initMap() {
		    var test = {lat:<%= @user.latitude %>, lng:<%= @user.longitude %>};
		    var map = new google.maps.Map(document.getElementById('map'), {
		              zoom: 15,
		              center: test
		              });
		    var transitLayer = new google.maps.TransitLayer();
		    transitLayer.setMap(map);

		    var contentString = '住所：<%= @user.address %>';
		    var infowindow = new google.maps.InfoWindow({
		      content: contentString
		    });


		    var marker = new google.maps.Marker({
		                  position:test,
		                  map: map,
		                  title: contentString
		                 });

		     marker.addListener('click', function() {
		       infowindow.open(map, marker);
		     });
		  }
		</script>

		<script async defer
  				src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['API_KEY'] %>&callback=initMap">
		</script>
		<style type="text/css">
		  #map { height: 250px;
		         width: 22%;}
		</style>

		<div id="map"></div>
	</div>
	<% end %>
</div>
<div class="col-xs-9">
	<h3><%= @user.name %>さんの書籍感想一覧<% if @user.id == current_user.id %>
		<%= link_to "新規投稿", new_book_path,class:"btn-lg btn-info  pull-right" %>
	<% end %></h3>
	<table class="table table-hover table-inverse">
   	    <thead>
		    <tr>
		        <th></th>
		        <th>タイトル</th>
		        <th>感想</th>
		        <th colspan="3"></th>
		    </tr>
	    </thead>
	    <tbody>
	        <% @books.each do |book| %>
		        <% if book.user == @user %>
					<tr>
						<td><%= attachment_image_tag @user, :profile_image, :fill, 20, 20, format: 'jpeg', class: " pull-left ", fallback: "no-image-icon.jpg" %> </td>
						<td class="book-title1"><%= link_to book.title, book_path(book) %></td>
						<td ><%= book.body %></td>
						<td><%= book.book_comments.count %>件コメント</td>
					</tr>
		        <% end %>
		     <% end %>
	    </tbody>
	</table>
</div>
<div>


</div>