config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'home/about' => 'home#about', as: 'about'
  root "home#top"

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }
  resources :books, only: [:new, :create, :index, :show, :edit, :update] do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  get'/search' => 'search#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
  	validates :title, presence:true, length: {minimum: 2,maximum: 20}
    validates :author, presence:true, length: {minimum: 1,maximum: 20}
	validates :body, presence:true, length: {maximum: 200}
	def self.search(method,word)
                if method == "forward_match"
                        @posts = Book.where("title LIKE?","#{word}%")
                elsif method == "backward_match"
                        @posts = Book.where("title LIKE?","%#{word}")
                elsif method == "perfect_match"
                        @posts = Book.where(title: "#{word}")
                elsif method == "partial_match"
                        @posts = Book.where("title LIKE?","%#{word}%")
                else
                        @posts = Book.all
                end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    def top
    end
    def new
      @book = Book.new
    end
    def create
  	  @book = Book.new(book_params)
  	  @book.user_id = current_user.id
  	  if @book.save
      flash[:notice] = "新規投稿しました。"
  	  redirect_to book_path(@book.id)
    else
      @book = Book.new
      flash[:notice] = "新規投稿できませんでした。"
      render 'new'
      end
    end
    def index
  	  @books = Book.page(params[:page]).reverse_order
    end
    def show
  	  @book = Book.find(params[:id])
      @user = @book.user
      @book_comment = BookComment.new
    end
    def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to books_path
    end
    def edit
      @book = Book.find(params[:id])
      unless @book.user_id == current_user.id
        redirect_to books_path
      end
    end

    def update
      @book = Book.find(params[:id])

      if @book.update(book_params)
        flash[:notice] = "編集完了しました。"
        redirect_to book_path(@book.id)
      else
        render 'edit'
      end
    end
		def book_params
  	  	params.require(:book).permit(:title, :author, :body)
		end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="body">
</div>
<p id="notice"></p>
<div class="col-md-6 col-md-offset-3">
	<h1>編集ページ</h1>
	　  <% if @book.errors.any? %>
		    <ul>
			    <%= @book.errors.count %><span>error</span>
			    <% @book.errors.full_messages.each do |message| %>
		　　　     <li><%= message %></li>
			    <% end %>
		    </ul>
	　  <% end %>
	    <%= form_for(@book) do |f| %>
		    <div class="field row">
	    	    <label>タイトル</label>
	    	    <%= f.text_field :title, class:"col-xs-12",class:"form-control" %>
	 	    </div>
	 	    <div class="field row">
			  <label>著者</label>
			  <%= f.text_field  :author, class:"col-xs-12",class:"form-control" %>
			</div><br>
	 	    <div class="field row">
		        <label>感想</label>
		        <%= f.text_area :body, class:"col-xs-12",class:"form-control" %>
		    </div><br>
	 	    <div class="actions row">
	    	    <%= f.submit '更新',class:"btn btn-primary col-xs-12" %>
	  	    </div>
	    <% end %>
	<%= link_to "戻る", book_path(@book) %> |
	<%= link_to "書籍一覧ページ", books_path %>
</div>
<div class="col-md-3"></div>

app/views/books/index.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="container2">
        <%= form_tag(search_path , method: :get) do %>
            <%= text_field(@search_content, :search_word)%>
            <%= select(@search_content, :search_model, [["書籍", "book"],["ユーザー","user"]])%>
            <%= select(@search_content, :search_method, [["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]])%>
            <%= submit_tag "検索" %>
        <% end %>
      </div>
    </div>
  </div>

</div>
<div class="col-xs-12">
  <h3>書籍感想一覧</h3>
    <table class="table">
      <thead>
        <tr>
          <th>ユーザー</th>
          <th>タイトル</th>
          <th>感想</th>
        </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user_id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 20, 20, format: 'jpeg', class: " pull-left ", fallback: "no_image.jpg",size:'20x20' %><br><%= book.user.name %>さん<% end %></td>
            <td><%= link_to book.title,book_path(book) %></td>
            <td><%= book.body %></td>
            <td>
              <div id="favorites_buttons_<%= book.id %>">
              <%= render partial: 'favorites/favorite', locals: { book: book} %>
              </div>
            </td>
            <td><%= book.book_comments.count %>件コメント</td>
          </tr>
         <% end %>
         <%= paginate @books %>
      </tbody>
    </table>
</div>


app/views/books/new.html.erb
<div class="body">
</div>
<div class="body">
</div>
  <% if @book.errors.any? %>
    <ul>
        <%= @book.errors.count %><span>error</span>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
  <% end %>
  <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
  <% end %>

　<h3>新規投稿</h3>
  <%= form_for(@book) do |f| %>
    <div class="field row">
        <label>タイトル</label>
        <%= f.text_field :title, class:"col-xs-12",class:"form-control" %>
    </div>
    <div class="field row">
        <label>著者</label>
        <%= f.text_field  :author, class:"col-xs-12",class:"form-control" %>
    </div><br>
    <div class="field row">
        <label>感想</label>
        <%= f.text_area :body, rows:'5', class:"col-xs-12",class:"form-control" %>
    </div><br>
    <div class="actions row center">
        <%= f.submit '投稿',class:"btn btn-primary" %>
    </div>
<% end %>

app/views/books/show.html.erb
<div class="body">
</div>
<% if flash[:notice] %>
    <div class="flash">
      <%= flash[:notice] %>
    </div>
<% end %>

<div class="col-xs-12">
  <div class="body3"></div>
  <table class="table">
    <thead>
      <tr>
        <th>ユーザー名</th>
        <th>タイトル</th>
        <th>著者</th>
        <th>感想</th>
        <th colspan="3"></th>
      </tr>
    <tbody>
      <tr>
        <td>
          <%= link_to user_path(@user) do %>
            <%= attachment_image_tag @user, :profile_image_id, :fill, 20, 20, format: 'jpeg', class: " pull-left ", fallback: "no_image.jpg",size:'20x20' %>
            <br><%= @user.name %>さん
          <% end %>
        </td>
        <td><%= @book.title %></td>
        <td><%= @book.author %></td>
        <td><%= @book.body %></td>
        <% if @user == current_user %>
        <td><%= link_to "編集", edit_book_path(@book),class:"btn-sm btn-success" %></td>
        <td><%= link_to "削除", destroy_book_path(@book), class:"btn-sm btn-danger",method: :delete, "data-confirm" => "本当に消しますか？" %></td>
        <% end %>
        <td>
          <div id="favorites_buttons_<%= @book.id %>">
            <%= render partial: 'favorites/favorite', locals: { book: @book} %>
          </div>
        </td>
        <td><%= @book.book_comments.count %>件コメント</td>
      </tr>
    </tbody>
  </table>
  <h3>コメント欄</h3>
  <table id="book_comment">
    <%= render 'book_comments/comment', book: @book %>
  </table>
  <br>
  <%= form_with(model: [@book, @book_comment] ) do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
    </div>
  </div>
  <%= f.submit "送信する", class: "btn btn-primary btn-base-1 mt-20 pull-right" %>
  <% end %>
  <div class="body3">
    <%= link_to "一覧に戻る", books_path %>
  </div>
</div>
