config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'home/about' => 'home#about', as: 'about'
  root "home#top"

  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }
  resources :books, only: [:new, :create, :index, :show, :edit, :update] do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  get'/search' => 'search#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span class="header glyphicon glyphicon-search">SearchBook</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "  マイページ", user_path(current_user) , class:"glyphicon glyphicon-home" %></li>
              <li><%= link_to "  ユーザー", users_path , class:"glyphicon glyphicon-user" %></li>
              <li><%= link_to "  書籍", books_path ,class:"glyphicon glyphicon-search" %></li>
              <li><%= link_to "  ログアウト", destroy_user_session_path, method: :delete ,class:"glyphicon glyphicon-log-out" %></li>
            <% else %>
              <li><%= link_to "  Home",root_path , class:"glyphicon glyphicon-home" %></li>
              <li><%= link_to "  About",about_path , class:"glyphicon glyphicon-link" %></li>
              <li><%= link_to "  新規登録", new_user_registration_path ,class:"glyphicon glyphicon-edit" %></li>
              <li><%= link_to "  ログイン", new_user_session_path, class:"glyphicon glyphicon-log-in" %></li>
            <% end %>

          </ul>
        </nav>
      </div>
    </header>
    <% if user_signed_in? %>
      

        <div class="container">
          <div class="row">
            <%= yield %>
          </div>
        </div>

      <footer>
        <div class="body2">
          <div class="container">
            <div class="row">
              <div class="col-xs-3 col-xs-offset-9">
                <p>CopyRight SearchBook.inc</p>
              </div>
            </div>
          </div>
        </div>
      </footer>
    <% else %>
      <div class="body3">
        <div class="container">
          <div class="row">
            <%= yield %>
          </div>
        </div>
      </div>
      <footer>
          <div class="container">
            <div class="row">
              <div class="col-xs-3 col-xs-offset-9">
                <p>CopyRight SearchBook.inc</p>
              </div>
            </div>
          </div>
      </footer>
    <% end %>
  </body>
</html>